### ISSUE TITLE
Commit taxel positions for `LEFT_FOOT`

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-taxel-positions#1]
@prashanthr05 extracted the triangle positiions for `LEFT_FOOT` patch from iCub v2.5 Creo Mechanics files. 

We should commit in this repo the raw data extracted from the CAD, and the script for generating the taxel positions from the raw data. 

An initial outcome for this script will be a `left_foot.txt` file (similar to the one already present in https://github.com/robotology/icub-main/tree/master/app/skinGui/conf/positions , that are used by the [`skinManager` module](http://wiki.icub.org/brain/group__icub__skinManager.html)).

This file follow this format: each line represent a taxel, using this format:

```
xPos yPos zPos xNorm yNorm zNorm
```

Where `xPos yPos zPos` is the position of the taxel in the `l_foot_dh_frame` frame (as discussed in https://github.com/robotology/icub-main/issues/124 ) and `xNorm yNorm zNorm` will be the normal to the taxel, that for the foot patch is constant and always vertical. 

For now we can just try to output this file with the position expressed in the `l_sole` frame, once we have the script working it will be trivial to change the positions to use the `l_foot_dh_frame`.

**Comment by traversaro** [comment]
fyi @matejhof @alecive

**Comment by alecive** [comment]
@traversaro  what is the `l_sole` frame?

**Comment by traversaro** [comment]
It is like the usual end effector frame (`l_foot_dh_frame`) for the legs iKinChain, but with the orientation X-FRONT, Y-LEFT, Z-UP .

**Comment by alecive** [comment]
@traversaro @prashanthr05  why the taxel positions for the foot as extracted from cad are still not in `icub-main`?

**Comment by traversaro** [comment]
I don't think anyone has verified the positions serialization.
