### ISSUE TITLE
Define triangle ordering for LEFT_FOOT SkinPart

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-taxel-positions#2]
For each "SkinPart" of skin (i.e. group of triangles mounted on a link) there is a triangle ordering, that is used on the real robot for outputting taxel values on the `/icub/skin/*` ports. 
We should properly document this triangle ordering, starting from the LEFT_FOOT patch. 

Some information can be extracted from the iCubSkinGui configuration files, available in: https://github.com/robotology/icub-main/tree/master/app/skinGui and the iCubSkinGui source code, available in https://github.com/robotology/icub-main/tree/master/src/tools/iCubSkinGui-qt/plugin .

**Comment by traversaro** [comment]
@alecive any advice for @prashanthr05  ?

**Comment by alecive** [comment]
Sorry I read the notification only now. What are you exactly trying to get?

**Comment by traversaro** [comment]
The mapping between the triangles in the skin patch and the order of the taxels as published in the `/icub/skin/left_foot` port.

**Comment by alecive** [comment]
As far as I know, there is no mainstream methodology for this. @ale-git should have more information, though (keep me updated :) ).

**Comment by traversaro** [comment]
Issue moved to https://github.com/robotology/icub-model-generator/issues/98 .
