### ISSUE TITLE
positions files generated for iCub skin V2 forearm seem wrong

### ISSUE THREAD

**Issue by matejhof** [robotology-playground/icub-taxel-positions#3]
I wanted to check the positions files that @traversaro and @towardthesea generated, before we can give green light to the production to distribute those files with V2 skin iCubs (as rightly requested by @pattacini ), but simple matlab plotting seems to reveal that the new files are wrong. 
Please see the attached .zip where you have the plots and a script plotting both V1 and V2.  
[forearmV1vsV2.zip](https://github.com/robotology-playground/icub-taxel-positions/files/701675/forearmV1vsV2.zip)

So any work relying on those positions now should take this into account. Using the old files would do a better job for know (even though there would be big problems on the upper small patch).
Until this is solved, we should go back in the blackie configuration in `skinManAll.ini` - putting back:

-  positions/left_forearm_mesh.txt 
- positions/right_forearm_mesh.txt

as per https://github.com/robotology/icub-main/blob/master/app/skinGui/conf/skinManAll.ini

@traversaro , @towardthesea, will you be able to fix it?

**Comment by towardthesea** [comment]
Sorry @matejhof , the calculation was done by this repo [icub-model-generator](https://github.com/robotology-playground/icub-model-generator)

**Comment by matejhof** [comment]
Ok, this has been solved by https://github.com/robotology-playground/icub-model-generator/commit/3983cd704f2835780567284244a426dec2790e8e

And fixed in `icub-main` here: https://github.com/robotology/icub-main/commit/ab19cf6a94fd3cea60988e8cfb43d7696536d2ac
